gcp_project: ascn2021
gcp_zone: europe-west1-b
gcp_region: europe-west1
gcp_auth_kind: serviceaccount
gcp_cred_file: '../ascn2021-service.json'

number_wikiserver_instances: 3

ansible_user: ze_nuno_baptis_martins_gmail_com
ansible_ssh_private_key_file: "{{ lookup('file', '~/.ssh/google_compute_engine') }}"

db_name: wiki
db_user_name: test_user
db_user_password: password

metricbeat_version: 7.16.2
elastic_search_version: 7.16.2
kibana_version: 7.16.2
